export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const GET_ACTIVITY_METADATA = 'GET_ACTIVITY_METADATA';
export const GET_ACTIVITY_OPTIONS = 'GET_ACTIVITY_OPTIONS';
export const SELECT_ACTIVITY = 'SELECT_ACTIVITY';
export const ADD_LOG = 'ADD_LOG';
